# Generated by Django 2.0.2 on 2018-03-21 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='tipo',
            field=models.CharField(choices=[('1', 'Biblioteca'), ('2', 'Insumos'), ('3', 'Foto')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 19, 17, 26, 620029), verbose_name='Fecha de Publicacion'),
        ),
    ]
