# Generated by Django 2.0.3 on 2018-03-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180327_0120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
