# Generated by Django 2.0.5 on 2018-05-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180518_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texto',
            old_name='orden2',
            new_name='orden',
        ),
    ]
