# Generated by Django 2.0.2 on 2018-03-21 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180321_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 20, 12, 0, 791298, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='tipo',
            field=models.CharField(choices=[(1, 'Biblioteca'), (2, 'Insumos'), (3, 'Foto')], default=1, max_length=1),
        ),
    ]
