# Generated by Django 2.0.3 on 2018-05-07 15:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='respuesta',
            field=tinymce.models.HTMLField(),
        ),
    ]
