# Generated by Django 2.0.3 on 2018-03-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180326_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Biblioteca'), (2, 'Insumos')], default=1),
        ),
    ]
