# Generated by Django 2.0.2 on 2018-03-21 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 19, 17, 26, 622890), verbose_name='Fecha de Publicacion'),
        ),
    ]
