# Generated by Django 2.0.3 on 2018-05-08 16:03

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 16, 3, 46, 524979), verbose_name='Fecha de fin del Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 16, 3, 46, 524950), verbose_name='Fecha del Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='importante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=tinymce.models.HTMLField(),
        ),
    ]
