# Generated by Django 2.0.5 on 2018-05-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_auto_20180518_1928'),
        ('calendario', '0006_auto_20180524_1650'),
    ]

    operations = [
    ]
