# Generated by Django 2.0.3 on 2018-03-26 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0007_auto_20180321_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Publicacion'),
        ),
    ]
