# Generated by Django 2.0.3 on 2018-07-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0011_auto_20180605_1624'),
        ('calendario', '0013_auto_20180528_1647'),
    ]

    operations = [
    ]
