# Generated by Django 2.0.3 on 2018-03-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20180327_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='portada',
            field=models.FileField(default='/archivos/defaults/noimage.gif', upload_to='portadas/'),
        ),
    ]
