# Generated by Django 2.0.5 on 2018-05-18 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('portada', models.FileField(upload_to='fotos/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='fotos/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encontrate.Album')),
            ],
        ),
    ]
