# Generated by Django 2.0.5 on 2018-05-18 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encontrate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicacion'),
        ),
    ]
