# Generated by Django 2.0.5 on 2018-05-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encontrate', '0002_foto_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='pub_date',
        ),
    ]
