# Generated by Django 2.0.3 on 2018-05-18 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_auto_20180518_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 28, 20, 406126), verbose_name='Fecha de fin del Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 19, 28, 20, 406074), verbose_name='Fecha del Evento'),
        ),
    ]
