# Generated by Django 2.0.3 on 2018-03-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='resumen',
        ),
    ]
