# Generated by Django 2.0.3 on 2018-03-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_remove_thread_resumen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
