# Generated by Django 2.0.3 on 2018-03-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_auto_20180327_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforo',
            name='icono',
            field=models.FileField(upload_to='icono'),
        ),
    ]
